name: 'Giphy PR Comment'
description: 'Add a Giphy GIF comment to new pull requests.'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  giphy-api-key:
    description: 'Giphy API Key'
    required: true
outputs:
  comment-url:
    description: 'URL of the Giphy GIF comment added to the pull request.'
runs:
  using: 'node16'
  main: 'dist/index.js'